apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gfsa-fe-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ""
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
            name: gfsa-fe
            port:
              number: 80
      - path: /qa
        pathType: Prefix
        backend:
          service:
            name: gfsa-fe
            port:
              number: 80
      - path: /uat
        pathType: Prefix
        backend:
          service:
            name: gfsa-fe
            port:
              number: 80
